dataset:
  edge_encoder: true
  edge_encoder_name: Bond
  format: OGB
  name: ogbg-molpcba
  node_encoder: true
  node_encoder_name: Atom+RWSE
  task: graph
  task_type: classification_multilabel
  transductive: false
gnn:
  act: gelu
  agg: add
  batchnorm: true
  dim_inner: 1024
  dropout: 0.4
  head: peak_mlp_graph
  layer_type: gatedgcnconv
  layers_mp: 6
  layers_post_mp: 1
  layers_pre_mp: 0
metric_best: ap
model:
  edge_decoding: dot
  graph_pooling: mean
  loss_fun: cross_entropy
  type: custom_gnn
optim:
  base_lr: 0.001
  max_epoch: 75
  num_warmup_epochs: 5
  optimizer: adamW
  scheduler: cosine_with_warmup
  weight_decay: 0.0
out_dir: tests/results
posenc_RWSE:
  dim_pe: 28
  enable: true
  kernel:
    times_func: range(1,17)
  model: Linear
  raw_norm_type: BatchNorm
share:
  dim_in: 2
  dim_out: 128
  num_splits: 3
train:
  batch_size: 512
  ckpt_period: 100
  eval_period: 1
  mode: custom
hsg:
  mask_hsg_edges: true
  mask_hsg_nodes: true
  edge_reduce_type: mode
  use_edge_onehot: true
  use_node_onehot: true
  num_hierarchy_nodes:
  - -1
wandb:
  # entity: insert_name
  name: molpcba_gatedgcn
  project: hsg
  use: true
