dataset:
  edge_encoder: true
  edge_encoder_bn: false
  edge_encoder_name: VOCMaskedEdge
  format: PyG-VOCSuperpixels
  name: edge_wt_region_boundary
  node_encoder: true
  node_encoder_bn: false
  node_encoder_name: VOCMaskedNode
  slic_compactness: 30
  task: graph
  task_type: classification
  transductive: false
gnn:
  act: gelu
  agg: add
  dim_inner: 140
  dropout: 0.2
  head: inductive_masked_node
  layer_type: gcnconv
  layers_mp: 10
  layers_post_mp: 2
  layers_pre_mp: 0
  residual: true
metric_best: f1
model:
  edge_decoding: dot
  loss_fun: weighted_cross_entropy
  type: custom_gnn
optim:
  base_lr: 0.001
  max_epoch: 200
  num_warmup_epochs: 10
  optimizer: adamW
  scheduler: cosine_with_warmup
  weight_decay: 0.0
out_dir: results
posenc_LapPE:
  dim_pe: 16
  eigen:
    eigvec_norm: L2
    laplacian_norm: sym
    max_freqs: 10
  enable: false
  layers: 2
  model: Transformer
  n_heads: 4
  raw_norm_type: none
share:
  dim_in: 14
  dim_out: 21
  num_splits: 3
train:
  batch_size: 50
  ckpt_period: 100
  eval_period: 1
  mode: custom
hsg:
  num_hierarchy_nodes:
  - -1
  mask_hsg_edges: true
  mask_hsg_nodes: true
  use_edge_onehot: true
  use_node_onehot: true
wandb:
  # entity: insert_name
  name: pascalvoc_gcn
  project: hsg
  use: true
