dataset:
  edge_encoder: true
  edge_encoder_bn: false
  edge_encoder_name: Bond
  format: OGB
  name: peptides-functional
  node_encoder: true
  node_encoder_bn: false
  node_encoder_name: Atom
  task: graph
  task_type: classification_multilabel
  transductive: false
gnn:
  act: gelu
  dim_inner: 235
  dropout: 0.1
  head: mlp_graph
  layer_type: gcnconv
  layers_mp: 6
  layers_post_mp: 3
  layers_pre_mp: 0
  residual: true
metric_best: ap
model:
  graph_pooling: mean
  loss_fun: cross_entropy
  type: custom_gnn
optim:
  base_lr: 0.001
  clip_grad_norm: true
  max_epoch: 250
  num_warmup_epochs: 5
  optimizer: adamW
  scheduler: cosine_with_warmup
  weight_decay: 0.0
out_dir: results
posenc_LapPE:
  dim_pe: 16
  eigen:
    eigvec_norm: L2
    laplacian_norm: none
    max_freqs: 10
  enable: false
  layers: 2
  model: DeepSet
  raw_norm_type: none
posenc_RWSE:
  dim_pe: 28
  enable: false
  kernel:
    times_func: range(1,21)
  model: Linear
  raw_norm_type: BatchNorm
share:
  dim_in: 9
  dim_out: 10
  num_splits: 3
train:
  batch_size: 200
  ckpt_period: 100
  eval_period: 1
  mode: custom
hsg:
  mask_hsg_edges: true
  mask_hsg_nodes: true
  edge_reduce_type: mode
  use_edge_onehot: true
  use_node_onehot: true
  num_hierarchy_nodes:
  - 0.5
  - -1
wandb:
  # entity: insert_name
  name: pept-func_gcn
  project: hsg
  use: true
